neuf=read.csv("C:/Users/tfillon/Downloads/dpe-v2-logements-neufs.csv", header = TRUE, dec = ".", sep = ",")
exist=read.csv("C:/Users/tfillon/Downloads/dpe-v2-logements-existants.csv", header = TRUE, dec = ".", sep = ",")
dim(exist)
dim(neuf)
neuf$Période_construction="2019;2024"
exist$Logement="ancien"
neuf$Logement="neuf"
col_commune=intersect(colnames(exist),colnames(neuf))
df <- rbind(exist[,col_commune], neuf[,col_commune])
View (df)
df$Date_réception_DPE_année=substr(df$Date_réception_DPE,start=1,stop=4)
df$calcul=df$Coût_chauffage + df$Coût_éclairage + df$Coût_ECS + df$Coût_refroidissement + df$Coût_auxiliaires
df$verif=ifelse(df$Coût_total_5_usages == df$calcul , yes = "oui", no = "non")
fmt_percent(df$Coût_chauffage_prc)=df$Coût_chauffage/df$calcul
by(df,df$Etiquette_DPE,nrow)	
by(df,df$Date_réception_DPE_année,nrow)
by(df,df$Logement,nrow)
by(df,df$Type_bâtiment,nrow)
by(df,df$Type_installation_chauffage,nrow)
x=table(df$Type_installation_chauffage)/nrow(df)
by(df,df$Période_construction,nrow)
View(x)
mean(df$Surface_habitable_logement,na.rm = TRUE)
mean(df$Coût_chauffage,na.rm = TRUE)
quantile(df$Coût_ECS, probs = seq(from =0.1, to =0.9 ,by =0.1))
 cor(x = df$Surface_habitable_logement, y = df$Coût_chauffage, method = "pearson",use="complete.obs")
var=c(df$Coût_total_5_usages,df$Coût_chauffage,df$Coût_éclairage,df$Coût_ECS,df$Coût_refroidissement, df$Coût_auxiliaires, df$Surface_habitable_logement , df$Emission_GES_5_usages)
plot(var,col="cyan")
install.packages("dplyr")
library("dplyr")
 dfappartement=filter(df,df$Type_bâtiment=="appartement")
 dfdefg=filter(df,Etiquette_DPE %in%c("D","E","F","G"))
 filter(df,df$Période_construction=="avant 1948")
 filter(df,df$Surface_habitable_logement>mean(df$Surface_habitable_logement,na.rm=TRUE))
arrange(data=df,df$Conso_5_usages.m._é_finale) 
addresse=read.csv("C:/Users/tfillon/Downloads/adresses-69.csv",header = TRUE, dec = ".", sep = ";")
left_join(addresse$id,addresse$lat,addresse$lon,)
